(()=>{
 const ws=window.WujiWorkspace,$=id=>document.getElementById(id);if(!ws)return;
 const page=document.createElement('section');page.id='page-doctor';page.className='workspace-page';page.hidden=true;
 page.innerHTML='<header class="page-heading"><h2 data-i18n="doctor"></h2><p>Wuji Doctor</p></header><div class="page-body doctor-body"><p id="doctor-scope" class="hint"></p><label for="doctor-serial" id="doctor-serial-label"></label><input id="doctor-serial" autocomplete="off" spellcheck="false" maxlength="80"><div class="button-row"><button id="doctor-version"></button><button id="doctor-run" class="primary"></button><a id="doctor-download" href="/api/doctor/report" download hidden></a></div><p id="doctor-status" role="status"></p><div id="doctor-rows"></div><details><summary id="doctor-raw-label"></summary><pre id="doctor-raw"></pre></details><a id="doctor-docs" href="https://docs.wuji.tech/docs/en/wuji-cli/latest/doctor/" target="_blank" rel="noopener"></a></div>';
 document.querySelector('.page-area').append(page);ws.views.doctor=page.querySelector('.page-body');
 const link=document.createElement('a');link.href='#doctor';link.dataset.page='doctor';link.innerHTML='<svg viewBox="0 0 26 24" aria-hidden="true"><path d="M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0 M6 12h4l2-5 3 10 2-5h5"/></svg><span data-i18n="doctor"></span>';
 document.querySelector('.directory').insertBefore(link,document.querySelector('.nav-advanced'));
 let state=null,result=null,sending=false;const t=(zh,en)=>window.WujiLocale.lang==='en'?en:zh;
 function translate(){page.querySelector('h2').textContent=t('官方诊断','Diagnostics');link.querySelector('span').textContent=t('官方诊断','Diagnostics');$('doctor-scope').textContent=t('调用官方CLI，检查环境、网络及设备。不会执行动作、标定或升级。缺少官方诊断项显示“跳过”，不等于电机验收通过。','Runs the official CLI for environment, network and device checks. No motion, calibration or upgrade. Skipped checks do not validate hand motors.');$('doctor-serial-label').textContent=t('设备序列号（可空，留空自动发现）','Device serial (optional; empty discovers devices)');$('doctor-version').textContent=t('检查 CLI','Check CLI');$('doctor-run').textContent=t('运行官方诊断','Run official diagnostics');$('doctor-download').textContent=t('导出报告','Export report');$('doctor-raw-label').textContent=t('官方原始输出','Official raw output');$('doctor-docs').textContent=t('查看官方诊断说明','Official diagnostic documentation');render();}
 function render(){const busy=sending||result?.running,connected=state?.connection!=='disconnected'||!!state?.glove?.busy;$('doctor-run').disabled=busy||connected;$('doctor-version').disabled=busy||connected;$('doctor-serial').disabled=busy;$('doctor-download').hidden=!result?.report;
  $('doctor-status').textContent=busy?t('正在检查，请稍候…','Checking…'):result?.error|| (result?.report?t('诊断已结束 · 官方退出码 ','Finished · official exit code ')+result.report.exit_code:connected?t('请先断开设备连接，再运行独立诊断。','Disconnect the SDK session before diagnostics.'):t('尚未运行。控制端和CLI路径在“连接与校准”设置。','Not run. Set the controller and CLI path in Connection.'));
  const report=result?.report,container=$('doctor-rows');container.replaceChildren();
  for(const row of report?.rows||[]){const line=document.createElement('div');line.className='doctor-row';line.style.paddingLeft=Math.min(row.depth,12)*14+'px';const badge=document.createElement('span');badge.className='doctor-badge';badge.dataset.status=row.status;badge.textContent=({pass:t('通过','Pass'),warn:t('提示','Warning'),fail:t('失败','Fail'),skip:t('跳过','Skipped'),group:t('分组','Group'),unknown:t('未知','Unknown')})[row.status]||row.status;const content=document.createElement('div'),label=document.createElement('strong'),detail=document.createElement('p');label.textContent=row.label+(row.sn?' · '+row.sn:'');detail.textContent=[row.summary,row.tip].filter(Boolean).join(' · ');content.append(label,detail);line.append(badge,content);container.append(line);}
  $('doctor-raw').textContent=report?[report.stdout,report.stderr,report.parse_error].filter(Boolean).join('\n'):'—';
 }
 async function poll(){try{const r=await fetch('/api/doctor',{cache:'no-store'});if(r.ok){result=await r.json();render();}}catch{}}
 async function run(name){sending=true;render();try{const s=await(await fetch('/api/state')).json();const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json','X-Console-Token':s.csrf},body:JSON.stringify({name,serial:$('doctor-serial').value.trim()})});const body=await r.json();if(!r.ok)throw Error(body.error);await poll();}catch(e){result={error:e.message};}finally{sending=false;render();}}
 $('doctor-version').addEventListener('click',()=>run('doctor_version'));$('doctor-run').addEventListener('click',()=>run('doctor_run'));
 window.addEventListener('console-state',e=>{state=e.detail;if(!page.hidden)render();});window.addEventListener('wuji-language',translate);window.addEventListener('workspace-page',()=>{if(location.hash==='#doctor')poll();});setInterval(()=>{if(!page.hidden)poll();},1500);translate();ws.showPage();
})();
