(function(){
 const ws=window.WujiWorkspace;if(!ws)return;
 const block=document.createElement('details');block.className='installation';
 const title=document.createElement('summary'),form=document.createElement('form'),help=document.createElement('p'),status=document.createElement('p'),save=document.createElement('button');
 help.className='hint';status.setAttribute('role','status');save.type='submit';save.className='primary';
 const keys=['mode','host','port','username','agent_directory','python','cli','key_filename','known_hosts'],inputs={},texts={},wrappers={};
 const labels={mode:['控制方式','Controller mode'],host:['Linux主机','Linux host'],port:['SSH端口','SSH port'],username:['SSH用户','SSH user'],agent_directory:['控制程序目录','Controller directory'],python:['SDK Python路径','SDK Python path'],cli:['官方CLI路径','Official CLI path'],key_filename:['本机SSH私钥路径（可空）','Local SSH key path (optional)'],known_hosts:['本机known_hosts路径（可空）','Local known_hosts path (optional)']};
 keys.forEach(key=>{const label=document.createElement('label'),span=document.createElement('span'),input=document.createElement(key==='mode'?'select':'input');if(key==='mode'){input.add(new Option('本机 Ubuntu / Local Ubuntu','local'));input.add(new Option('远程 Linux（SSH）/ Remote Linux','ssh'));}else{input.type=key==='port'?'number':'text';input.autocomplete='off';input.spellcheck=false;}input.id='bridge-'+key;label.htmlFor=input.id;label.append(span,input);form.append(label);inputs[key]=input;texts[key]=span;wrappers[key]=label;});
 form.append(save,status);block.append(title,help,form);ws.views.connection.prepend(block);
 const edition=document.createElement('p');edition.className='studio-small';ws.views.interaction.prepend(edition);let info;
 function translate(){const en=document.documentElement.lang==='en',local=inputs.mode.value==='local';title.textContent=en?'Controller and diagnostic settings':'控制端与诊断设置';help.textContent=local?(en?'Ubuntu runs the SDK locally, without SSH or a virtual machine. Install the official SDK/CLI and select their paths. Saving does not connect or move the hand.':'Ubuntu本机运行SDK，无需SSH或虚拟机。安装官方SDK/CLI并填写路径；保存不会连接或启动手。'):(en?'Windows/macOS connect to a Linux SDK controller over SSH. Configure it later on the machine that will control the hand. No credentials are bundled.':'Windows/macOS通过SSH连接Linux控制端；可以到使用的电脑上再配置，不附带任何账户或密钥。');save.textContent=en?'Save settings':'保存设置';keys.forEach(k=>texts[k].textContent=labels[k][en?1:0]);['host','port','username','key_filename','known_hosts'].forEach(k=>wrappers[k].hidden=local);if(info)edition.textContent=info.optional_model?.installed?(en?'Private model loaded · offline Hand 2 left simulation recognition; hardware use is not enabled.':'已加载私有模型 · 二代左手离线仿真识别；未启用实机识别或抓取。'):(en?'No private model loaded. Import a data-only pack from the workbench menu.':'未加载私有模型，可在工作台菜单导入模型数据包。');}
 inputs.mode.addEventListener('change',translate);
 fetch('/api/installation').then(r=>r.json()).then(s=>{info=s;inputs.mode.querySelector('option[value="local"]').disabled=!s.local_controller_supported;keys.forEach(k=>inputs[k].value=s.bridge[k]);translate();}).catch(()=>status.textContent='无法读取配置 / Cannot load settings');
 form.addEventListener('submit',async e=>{e.preventDefault();save.disabled=true;try{const state=await(await fetch('/api/state')).json();const values=Object.fromEntries(keys.map(k=>[k,k==='port'?Number(inputs[k].value):inputs[k].value]));const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json','X-Console-Token':state.csrf},body:JSON.stringify({name:'bridge_config_save',values})});const result=await r.json();if(!r.ok)throw Error(result.error);status.textContent='已保存，尚未连接 / Saved, not connected';}catch(e){status.textContent=e.message;}finally{save.disabled=false;}});
 window.addEventListener('workbench-model-changed',async()=>{info=await(await fetch('/api/installation')).json();translate();});
 window.addEventListener('workspace-page',e=>{if(e.detail==='interaction')window.dispatchEvent(new Event('workbench-model-changed'));});
 translate();window.addEventListener('wuji-language',translate);
})();
