(function(){
  const ws=window.WujiWorkspace;if(!ws)return;
  const block=document.createElement('details');block.className='installation';
  const title=document.createElement('summary'),form=document.createElement('form'),help=document.createElement('p'),status=document.createElement('p'),save=document.createElement('button');
  help.className='hint';status.setAttribute('role','status');save.type='submit';save.className='primary';
  const keys=['host','port','username','agent_directory','python','key_filename','known_hosts'],inputs={};
  const labels={host:['控制端主机','Controller host'],port:['SSH端口','SSH port'],username:['SSH用户','SSH user'],agent_directory:['控制端程序目录','Controller directory'],python:['控制端Python路径','Controller Python'],key_filename:['本机SSH私钥路径（可空）','Local SSH key path (optional)'],known_hosts:['本机known_hosts路径（可空）','Local known_hosts path (optional)']},texts={};
  keys.forEach(key=>{const label=document.createElement('label'),span=document.createElement('span'),input=document.createElement('input');input.type=key==='port'?'number':'text';input.autocomplete='off';input.spellcheck=false;input.id='bridge-'+key;label.htmlFor=input.id;label.append(span,input);form.append(label);inputs[key]=input;texts[key]=span;});
  form.append(save,status);block.append(title,help,form);ws.views.connection.querySelector('.page-body').prepend(block);
  const edition=document.createElement('p');edition.className='studio-small';ws.views.interaction.querySelector('.page-body').prepend(edition);let info;
  function translate(){const en=document.documentElement.lang==='en';title.textContent=en?'Linux controller settings':'Linux控制端设置';help.textContent=en?'Hardware uses an explicitly configured Linux SDK controller. SSH keys stay on this computer. Verify the host with SSH first. Saving does not connect or move the hand.':'实机通过你配置的Linux SDK控制端连接。SSH密钥只留在本机；请先通过SSH核对主机指纹。保存不会连接或启动手。';save.textContent=en?'Save connection settings':'保存连接设置';keys.forEach(k=>texts[k].textContent=labels[k][en?1:0]);if(info){const research=info.edition.name==='research';edition.textContent=research?(en?'Research edition · trained model included for offline research. Real-hand calibration is still required.':'私有研究版 · 已附带训练模型供离线研究，实机使用仍需校准。'):(en?'Basic edition · no trained models included.':'公开基础版 · 不附带训练模型。');}}
  fetch('/api/installation').then(r=>r.json()).then(s=>{info=s;keys.forEach(k=>inputs[k].value=s.bridge[k]);translate();}).catch(()=>{status.textContent='无法读取连接配置 / Cannot load configuration';});
  form.addEventListener('submit',async e=>{e.preventDefault();save.disabled=true;try{const state=await(await fetch('/api/state')).json();const values=Object.fromEntries(keys.map(k=>[k,k==='port'?Number(inputs[k].value):inputs[k].value]));const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json','X-Console-Token':state.csrf},body:JSON.stringify({name:'bridge_config_save',values})});const result=await r.json();if(!r.ok)throw Error(result.error);status.textContent='已保存，尚未连接 / Saved, not connected';}catch(e){status.textContent=e.message;}finally{save.disabled=false;}});
  translate();window.addEventListener('wuji-language',translate);
})();
