(function(){
 const ws=window.WujiWorkspace;if(!ws)return;
 const block=document.createElement('details');block.className='installation';
 const title=document.createElement('summary'),form=document.createElement('form'),help=document.createElement('p'),status=document.createElement('p'),save=document.createElement('button');
 help.className='hint';status.setAttribute('role','status');save.type='submit';save.className='primary';
 const keys=['mode','host','port','username','agent_directory','python','cli','key_filename','known_hosts'],inputs={},texts={},wrappers={};
 const labels={mode:['控制方式','Controller mode'],host:['Linux主机','Linux host'],port:['SSH端口','SSH port'],username:['SSH用户','SSH user'],agent_directory:['控制程序目录','Controller directory'],python:['SDK Python路径','SDK Python path'],cli:['官方CLI路径','Official CLI path'],key_filename:['本机SSH私钥路径（可空）','Local SSH key path (optional)'],known_hosts:['本机known_hosts路径（可空）','Local known_hosts path (optional)']};
 keys.forEach(key=>{const label=document.createElement('label'),span=document.createElement('span'),input=document.createElement(key==='mode'?'select':'input');if(key==='mode'){input.add(new Option('本机 Ubuntu / Local Ubuntu','local'));input.add(new Option('远程 Linux（SSH）/ Remote Linux','ssh'));}else{input.type=key==='port'?'number':'text';input.autocomplete='off';input.spellcheck=false;}input.id='bridge-'+key;label.htmlFor=input.id;label.append(span,input);form.append(label);inputs[key]=input;texts[key]=span;wrappers[key]=label;});
 const passwordLabel=document.createElement('label'),passwordText=document.createElement('span'),password=document.createElement('input'),passwordHint=document.createElement('p'),forget=document.createElement('button');
 password.type='password';password.autocomplete='new-password';password.id='bridge-password';passwordLabel.htmlFor=password.id;passwordLabel.append(passwordText,password);passwordHint.className='hint';forget.type='button';
 form.append(passwordLabel,passwordHint,save,forget,status);block.append(title,help,form);ws.views.connection.prepend(block);
 const edition=document.createElement('p');edition.className='studio-small';ws.views.interaction.prepend(edition);let info;
 inputs.mode.add(new Option('Windows 内置 Linux / Built-in Linux','wsl'));
 inputs.mode.add(new Option('Mac 内置 Linux / Built-in Linux','macvm'));
 const managed=mode=>['wsl','macvm'].includes(mode);
 const runtimeCard=document.createElement('section');runtimeCard.className='panel runtime-card';const runtimeTitle=document.createElement('h3'),runtimeText=document.createElement('p'),runtimeStatus=document.createElement('p'),runtimeButton=document.createElement('button');runtimeStatus.setAttribute('role','status');runtimeButton.type='button';runtimeButton.className='primary';runtimeCard.append(runtimeTitle,runtimeText,runtimeButton,runtimeStatus);block.before(runtimeCard);const systemHelp=document.createElement('details'),systemTitle=document.createElement('summary'),systemButton=document.createElement('button');systemTitle.textContent='Windows 还没有 WSL 2？ / WSL 2 missing?';systemButton.textContent='安装 Windows 系统组件 / Install Windows components';systemButton.type='button';systemHelp.append(systemTitle,systemButton);runtimeCard.append(systemHelp);systemButton.onclick=async()=>{try{if(!window.pywebview?.api)throw Error('请在 Windows 软件中操作 / Open the Windows app');await window.pywebview.api.install_runtime_components();runtimeStatus.textContent='已请求 Windows 安装组件；若系统要求重启，重启后再点安装内置控制环境。 / Windows setup requested; restart if required, then install the controller.';}catch(e){runtimeStatus.textContent=e.message;}};
 function runtimeLabels(){
  const en=document.documentElement.lang==='en',r=info?.runtime;
  runtimeCard.hidden=!r?.supported;if(!r?.supported)return;
  const mac=r.mode==='macvm',selected=managed(info.bridge.mode);
  systemHelp.hidden=mac;
  runtimeTitle.textContent=en?'Built-in hand controller':'内置机械手控制环境';
  runtimeText.textContent=mac?(en?'Linux is included with this Mac app. The first setup installs the official SDK using the internet; subsequent starts are automatic. No VM window or SSH configuration.':'Mac 安装包已包含 Linux。首次准备需联网安装官方 SDK，之后自动启动，无需虚拟机窗口或 SSH 配置。'):(en?'A small Linux environment runs quietly with the workbench. No VMware window, SSH host or password. Setup never moves the hand.':'精简 Linux 环境由工作台在后台管理，无需打开 VMware、填写 SSH 地址或密码。安装不会让手运动。');
  runtimeButton.textContent=r.busy?(en?'Preparing…':'正在准备…'):r.ready?(selected?(en?'Built-in controller selected':'已使用内置控制环境'):(en?'Use built-in controller':'使用内置控制环境')):(en?'Set up built-in controller':'安装内置控制环境');
  runtimeButton.disabled=r.busy||(r.ready&&selected);
  const phases={checking:['正在校验组件','Verifying components'],importing:['正在准备 Linux 与 SDK，首次需要几分钟','Preparing Linux and SDK; first setup takes several minutes'],verifying:['正在检查官方 SDK','Checking the official SDK']};
  runtimeStatus.textContent=r.error||(r.busy?(phases[r.stage]?.[en?1:0]||r.stage):r.ready?(en?'Ready · Official SDK '+r.sdk_version+' · '+(mac?'Apple Virtualization':'WSL 2'):'已就绪 · 官方 SDK '+r.sdk_version+' · '+(mac?'Apple Virtualization':'WSL 2')):mac?(en?'Apple Silicon · macOS 13.5+ · 2 GB RAM · up to 12 GB disk. USB passthrough is not supported; Hand 1 uses an external Linux controller.':'Apple 芯片 · macOS 13.5+ · 2 GB 内存 · 最大 12 GB 磁盘。一代 USB 手暂需外部 Linux 控制端。'):(en?'One-time setup. WSL 2 may request administrator approval and a restart.':'首次安装一次。WSL 2 可能需要管理员确认及重启。'));
  for(const mode of ['wsl','macvm'])inputs.mode.querySelector('option[value="'+mode+'"]').disabled=!r.ready||(mode==='macvm')!==mac;
  if(selected){block.open=false;help.textContent=en?'The built-in controller is managed by the app.':'内置控制环境由软件自动管理。';keys.forEach(k=>wrappers[k].hidden=k!=='mode');}
 }
 function translate(){const en=document.documentElement.lang==='en',local=inputs.mode.value==='local';title.textContent=en?'Controller and diagnostic settings':'控制端与诊断设置';help.textContent=local?(en?'Ubuntu runs the SDK locally, without SSH or a virtual machine. Install the official SDK/CLI and select their paths. Saving does not connect or move the hand.':'Ubuntu本机运行SDK，无需SSH或虚拟机。安装官方SDK/CLI并填写路径；保存不会连接或启动手。'):(en?'Windows/macOS connect to a Linux SDK controller over SSH. Configure it later on the machine that will control the hand. No credentials are bundled.':'Windows/macOS通过SSH连接Linux控制端；可以到使用的电脑上再配置，不附带任何账户或密钥。');save.textContent=en?'Save settings':'保存设置';keys.forEach(k=>texts[k].textContent=labels[k][en?1:0]);['host','port','username','key_filename','known_hosts'].forEach(k=>wrappers[k].hidden=local);if(info)edition.textContent=info.optional_model?.installed?(en?'Private model loaded · offline Hand 2 left simulation recognition; hardware use is not enabled.':'已加载私有模型 · 二代左手离线仿真识别；未启用实机识别或抓取。'):(en?'No private model loaded. Import a data-only pack from the workbench menu.':'未加载私有模型，可在工作台菜单导入模型数据包。');}
 function credentialLabels(){const en=document.documentElement.lang==='en',supported=info?.credential?.supported&&inputs.mode.value==='ssh';passwordLabel.hidden=passwordHint.hidden=forget.hidden=!supported;passwordText.textContent=en?'SSH password (leave empty to keep saved)':'SSH 密码（留空保留已保存密码）';forget.textContent=en?'Forget saved password':'清除已保存密码';forget.disabled=!info?.credential?.saved;passwordHint.textContent=info?.credential?.saved?(en?'A password is saved in Windows Credential Manager for this host and user. A configured SSH key takes priority.':'此主机与用户已有密码保存在 Windows 凭据管理器；填写 SSH 密钥时优先使用密钥。'):(en?'Saved only in Windows Credential Manager. Never included in an export or installer.':'仅保存在 Windows 凭据管理器，不随导出或安装包分发。');}
 inputs.mode.addEventListener('change',()=>{keys.forEach(k=>wrappers[k].hidden=false);translate();credentialLabels();if(managed(inputs.mode.value))keys.forEach(k=>wrappers[k].hidden=k!=='mode');});
 async function reload(){const s=await(await fetch('/api/installation')).json();info=s;inputs.mode.querySelector('option[value="local"]').disabled=!s.local_controller_supported;keys.forEach(k=>inputs[k].value=s.bridge[k]);if(!s.controller_configured){block.open=!s.runtime?.supported;status.textContent='尚未配置控制端，保存后再连接 / Configure the controller before connecting';}translate();credentialLabels();runtimeLabels();}
 reload().catch(()=>status.textContent='无法读取配置 / Cannot load settings');
 async function send(data){const state=await(await fetch('/api/state')).json();const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json','X-Console-Token':state.csrf},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw Error(result.error);return result;}
 form.addEventListener('submit',async e=>{e.preventDefault();save.disabled=true;try{const values=Object.fromEntries(keys.map(k=>[k,k==='port'?Number(inputs[k].value):inputs[k].value]));if(managed(values.mode))await send({name:'runtime_select'});else await send({name:'bridge_config_save',values});if(password.value&&values.mode==='ssh')await send({name:'bridge_password_save',password:password.value});password.value='';await reload();status.textContent='已保存，尚未连接 / Saved, not connected';}catch(e){status.textContent=e.message;}finally{password.value='';save.disabled=false;}});
 forget.addEventListener('click',async()=>{forget.disabled=true;try{await send({name:'bridge_password_forget'});await reload();status.textContent='已清除密码，连接设置保留 / Password removed; settings kept';}catch(e){status.textContent=e.message;credentialLabels();}});
 runtimeButton.addEventListener('click',async()=>{runtimeButton.disabled=true;try{await send({name:info?.runtime?.ready?'runtime_select':'runtime_install'});await reload();}catch(e){runtimeStatus.textContent=e.message;runtimeButton.disabled=false;}});
 setInterval(async()=>{if(!info?.runtime?.busy)return;try{await reload();}catch{}},2000);
 window.addEventListener('workbench-model-changed',async()=>{info=await(await fetch('/api/installation')).json();translate();});
 window.addEventListener('workspace-page',e=>{if(e.detail==='interaction')window.dispatchEvent(new Event('workbench-model-changed'));});
 translate();credentialLabels();window.addEventListener('wuji-language',()=>{translate();credentialLabels();runtimeLabels();});
})();
