"""Editable demonstration defaults. Saving does not start hardware."""
KP = 3
KD = 0.04
CURRENT_LIMIT_A = 0.5
PATH_SPEED_RAD_S = 0.075
COMMAND_SPEED_RAD_S = 0.08
COMMAND_RATE_HZ = 1000
PROBE_SPEED_RAD_S = 0.05
MIN_TRANSITION_S = 1
POSE_HOLD_S = 1
OFFICIAL_ENDPOINT_HOLD_S = 0.5
OFFICIAL_RETURN_HOLD_S = 1
MAX_TRIAL_DURATION_S = 600
